### ISSUE TITLE
EnvCommandError on poetry install

### ISSUE THREAD

**Issue by UveshRajwani** [Floozutter/buzzspike#1]
C:\Users\Uvesh\Downloads\Compressed\buzzspike-main>poetry install
Creating virtualenv buzzspike-xmvOAOA4-py3.9 in C:\Users\Uvesh\AppData\Local\pypoetry\Cache\virtualenvs

  EnvCommandError

  Command C:\Users\Uvesh\AppData\Local\pypoetry\Cache\virtualenvs\buzzspike-xmvOAOA4-py3.9\Scripts\python.exe - errored with the following return code 1, and output:
  The system cannot find the path specified.
  input was : import sys

  if hasattr(sys, "real_prefix"):
      print(sys.real_prefix)
  elif hasattr(sys, "base_prefix"):
      print(sys.base_prefix)
  else:
      print(sys.prefix)

  at ~\.poetry\lib\poetry\utils\env.py:1075 in _run
      1071│                 output = subprocess.check_output(
      1072│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1073│                 )
      1074│         except CalledProcessError as e:
    → 1075│             raise EnvCommandError(e, input=input_)
      1076│
      1077│         return decode(output)
      1078│
      1079│     def execute(self, bin, *args, **kwargs):

C:\Users\Uvesh\Downloads\Compressed\buzzspike-main>

**Comment by Floozutter** [comment]
from these
- https://github.com/python-poetry/poetry/issues/1587
- https://github.com/python-poetry/poetry/issues/1895

it looks like there could be an issue with your `PATH`'s `python`?

**Comment by UveshRajwani** [comment]
ok
